# Generated by Django 5.1 on 2024-09-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='defaut category', max_length=255),
        ),
    ]
