# Generated by Django 5.1 on 2024-09-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='this is default snippet', max_length=255),
        ),
    ]
